controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    torso_forward_position_controller:
      type: position_controllers/JointGroupPositionController

    gripper_forward_position_controller:
      type: position_controllers/JointGroupPositionController

    left_gripper_controller:
      type: position_controllers/GripperActionController

    right_gripper_controller:
      type: position_controllers/GripperActionController

    cmd_vel_forward_controller:
      type: cmd_vel_forward_controller/CmdVelForwardController

    left_ft_sensor:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    right_ft_sensor:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    joint_admittance_controller:
      type: joint_admittance_controller/JointAdmittanceController

    joint_admittance_forward_position_controller:
      type: position_controllers/JointGroupPositionController

    odometry_broadcaster:
      type: rby1_controllers/OdometryBroadcaster

    head_forward_position_controller:
      type: position_controllers/JointGroupPositionController


{% if ros2_control_hardware_type == "real" %}
joint_state_broadcaster:
  ros__parameters:
    extra_joints:
      - left_wheel
      - right_wheel
# TODO: Remove once wheel joints & robotiq grippers are supported in prealpha_description/control/isaacsim.ros2_control.xacro
{% elif ros2_control_hardware_type == "isaacsim" %}
joint_state_broadcaster:
  ros__parameters:
    extra_joints:
      - left_wheel
      - right_wheel
      - right_robotiq_85_left_knuckle_joint
      - left_robotiq_85_left_knuckle_joint
{% endif %}

left_gripper_controller:
  ros__parameters:
{% if gripper == "builtin" %}
    joint: gripper_finger_l1
{% elif gripper == "robotiq" %}
    joint: left_robotiq_85_left_knuckle_joint
{% endif %}
    allow_stalling: true

right_gripper_controller:
  ros__parameters:
{% if gripper == "builtin" %}
    joint: gripper_finger_r1
{% elif gripper == "robotiq" %}
    joint: right_robotiq_85_left_knuckle_joint
{% endif %}
    allow_stalling: true


joint_trajectory_controller:
  ros__parameters:
    allow_partial_joints_goal: true
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
      - torso_0
      - torso_1
      - torso_2
      - torso_3
      - torso_4
      - torso_5

forward_position_controller:
  ros__parameters:
    joints:
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6

joint_admittance_forward_position_controller:
  ros__parameters:
    joints:
      - joint_admittance_controller/right_arm_0
      - joint_admittance_controller/right_arm_1
      - joint_admittance_controller/right_arm_2
      - joint_admittance_controller/right_arm_3
      - joint_admittance_controller/right_arm_4
      - joint_admittance_controller/right_arm_5
      - joint_admittance_controller/right_arm_6
      - joint_admittance_controller/left_arm_0
      - joint_admittance_controller/left_arm_1
      - joint_admittance_controller/left_arm_2
      - joint_admittance_controller/left_arm_3
      - joint_admittance_controller/left_arm_4
      - joint_admittance_controller/left_arm_5
      - joint_admittance_controller/left_arm_6

joint_admittance_controller:
  ros__parameters:
    joints:
    - right_arm_0
    - right_arm_1
    - right_arm_2
    - right_arm_3
    - right_arm_4
    - right_arm_5
    - right_arm_6
    - left_arm_0
    - left_arm_1
    - left_arm_2
    - left_arm_3
    - left_arm_4
    - left_arm_5
    - left_arm_6


torso_forward_position_controller:
  ros__parameters:
    joints:
      - torso_0
      - torso_1
      - torso_2
      - torso_3
      - torso_4
      - torso_5

gripper_forward_position_controller:
  ros__parameters:
    joints:
{% if gripper == "builtin" %}
      - gripper_finger_r1
      - gripper_finger_l1
{% elif gripper == "robotiq" %}
      - right_robotiq_85_left_knuckle_joint
      - left_robotiq_85_left_knuckle_joint
{% endif %}

cmd_vel_forward_controller:
  ros__parameters:
    joint: mobile_base

left_ft_sensor:
  ros__parameters:
    sensor_name: "left_ft_sensor"
    frame_id: "left_robotiq_85_base_link"

right_ft_sensor:
  ros__parameters:
    sensor_name: "right_ft_sensor"
    frame_id: "right_robotiq_85_base_link"

odometry_broadcaster:
  ros__parameters:
    frame_id: "odom"
    child_frame_id: "base_link"

head_forward_position_controller:
  ros__parameters:
    joints:
      - head_0
      - head_1
